name: Generate CSS from JSON

on:
  push:
    branches: [ main ]
    paths:
      - 'src/styles/theme.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/styles/theme.json'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate CSS from theme.json
      run: npm run generate-css

    - name: Commit and push changes
      run: |
        # Configure git
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        
        # Check if there are changes
        if [[ -n "$(git status --porcelain)" ]]; then
          git add src/styles/generated.css
          git commit -m "Update generated CSS from theme.json [skip ci]"
          git push
        else
          echo "No changes detected"
        fi