name: Theme Tokens Conversion

on:
  pull_request:
    paths:
      - 'src/styles/theme.json'
  push:
    branches:
      - main
      - tokens-update  # Added tokens-update branch
    paths:
      - 'src/styles/theme.json'
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message for CSS generation'
        required: false
        default: 'Update theme CSS files'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  convert-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Create output directory
        run: mkdir -p src/styles/theme-files
          
      - name: Clean theme.json file
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            const themePath = path.join(process.cwd(), 'src', 'styles', 'theme.json');
            
            try {
              // Read the theme file
              const themeData = JSON.parse(fs.readFileSync(themePath, 'utf8'));
              
              // Clean the $themes array if it exists
              if (themeData.$themes && Array.isArray(themeData.$themes)) {
                themeData.$themes = [];
                console.log('Cleaned $themes array in theme.json');
              } else {
                console.log('No $themes array found or already empty');
              }
              
              // Remove $metadata section if it exists
              if (themeData.$metadata) {
                delete themeData.$metadata;
                console.log('Removed $metadata section from theme.json');
              }
              
              // Write the cleaned file back
              fs.writeFileSync(themePath, JSON.stringify(themeData, null, 2));
              console.log('Wrote cleaned theme.json file');
            } catch (error) {
              console.error('Error processing theme.json:', error);
              process.exit(1);
            }
          "
      
      - name: Convert theme tokens
        run: |
          echo "Running convert-theme-tokens.js..."
          
          # Check if the script exists in src/styles/ first
          if [ -f "src/styles/convert-theme-tokens.js" ]; then
            node src/styles/convert-theme-tokens.js
          # Otherwise try src/utils/ location
          elif [ -f "src/utils/convert-theme-tokens.js" ]; then
            node src/utils/convert-theme-tokens.js
          else
            echo "Error: Could not find convert-theme-tokens.js in src/styles/ or src/utils/"
            exit 1
          fi
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet src/styles/theme-files || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Check generated files
        run: |
          echo "Generated CSS files:"
          find src/styles/theme-files -name "*.css" || echo "No CSS files found"
          
          echo "Total files generated:"
          find src/styles/theme-files -type f | wc -l
          
      - name: Commit changes if needed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Use custom commit message for manual dispatch, otherwise use default
          COMMIT_MESSAGE="${{ github.event.inputs.message || 'Update theme CSS files' }}"
          
          git add src/styles/theme-files/
          git add src/styles/theme.json
          git commit -m "$COMMIT_MESSAGE"
          git push
      
      - name: Output summary
        run: |
          echo "## Theme Token Conversion Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: $(git branch --show-current)" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: $(git rev-parse HEAD)" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.git-check.outputs.changes }}" == "true" ]; then
            echo "- Status: ✅ Changes detected and committed" >> $GITHUB_STEP_SUMMARY
            echo "- Generated files: $(find src/styles/theme-files -type f | wc -l)" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Status: ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
          fi