name: Theme Tokens Conversion

on:
  pull_request:
    paths:
      - 'src/styles/theme.json'
  push:
    branches:
      - main
      - tokens-update
    paths:
      - 'src/styles/theme.json'
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message for manual CSS generation'
        required: false
        default: 'Manual theme CSS generation'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  convert-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create output directory
        run: mkdir -p src/styles/theme-files
      
      - name: Generate CSS from theme.json
        run: |
          echo "Running JsonToCssSplit.js"
          node src/utils/JsonToCssSplit.js src/styles/theme.json src/styles/theme-files
      
      - name: Check generated files
        run: |
          echo "Generated CSS files:"
          find src/styles/theme-files -name "*.css" || echo "No CSS files found"
          
          echo "Total files generated:"
          find src/styles/theme-files -type f | wc -l
      
      - name: Debugging information
        run: |
          echo "Current directory contents:"
          pwd
          ls -la
          
          echo "src/styles contents:"
          ls -la src/styles
          
          echo "src/styles/theme-files contents:"
          ls -la src/styles/theme-files || echo "theme-files directory does not exist"
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Use custom commit message for manual dispatch, otherwise use default
          COMMIT_MESSAGE="${{ github.event.inputs.message || 'Update theme CSS files using JsonToCssSplit' }}"
          
          # Check if there are any changes
          if [[ -n "$(git status --porcelain src/styles/theme-files)" ]]; then
            echo "Changes detected in theme-files"
            git add src/styles/theme-files/
            git commit -m "$COMMIT_MESSAGE" || echo "Nothing