name: Theme Tokens Conversion

on:
  pull_request:
    paths:
      - 'src/styles/theme.json'
  push:
    branches:
      - main
      - tokens-update
    paths:
      - 'src/styles/theme.json'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update CSS files even if no changes detected'
        type: boolean
        default: true

# Add this section
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  convert-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Create output directory
        run: mkdir -p src/styles/theme-files
      
      - name: Run JSON to CSS conversion
        run: |
          node src/utils/JsonToCssSplit.js src/styles/theme.json src/styles/theme-files
      
      - name: Create theme loader
        run: |
          cat > src/styles/theme-files/theme-loader.js << 'EOF'
          /**
           * Dynamic CSS loader for theme files
           * Auto-generated
           */
          class ThemeLoader {
            constructor() {
              this.loadedStylesheets = new Map();
              this.defaultMode = 'light';
              this.defaultPlatform = this.detectPlatform();
              this.initialized = false;
            }
          
            /**
             * Detect the current platform
             * @returns {string} - Detected platform (desktop, mobile, etc.)
             */
            detectPlatform() {
              // Basic platform detection logic
              const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
              return isMobile ? 'mobile' : 'desktop';
            }
          
            /**
             * Load a CSS file dynamically
             * @param {string} fileName - The CSS file to load
             * @param {string} id - Unique identifier for the stylesheet
             * @returns {Promise} - Promise that resolves when the stylesheet is loaded
             */
            loadStylesheet(fileName, id) {
              return new Promise((resolve, reject) => {
                // If already loaded, resolve immediately
                if (this.loadedStylesheets.has(id)) {
                  resolve();
                  return;
                }
          
                const link = document.createElement('link');
                link.rel = 'stylesheet';
                link.href = fileName;
                link.id = id;
          
                link.onload = () => {
                  this.loadedStylesheets.set(id, link);
                  resolve();
                };
          
                link.onerror = () => {
                  reject(new Error(`Failed to load ${fileName}`));
                };
          
                document.head.appendChild(link);
              });
            }
          
            /**
             * Initialize the theme by loading base CSS
             * @returns {Promise} - Promise that resolves when base CSS is loaded
             */
            async initialize() {
              if (this.initialized) {
                return;
              }
          
              try {
                // Load base CSS first
                await this.loadStylesheet('base.css', 'theme-base');
                
                // Load system CSS
                await this.loadStylesheet('system.css', 'theme-system');
                
                this.initialized = true;
              } catch (err) {
                console.error('Error initializing theme:', err);
              }
            }
          
            /**
             * Set the current theme data attributes on the document
             * @param {string} mode - The mode to set
             * @param {string} platform - The platform to set
             */
            setThemeAttributes(mode, platform) {
              document.documentElement.setAttribute('data-mode', mode);
              document.documentElement.setAttribute('data-platform', platform);
            }
          
            /**
             * Load the appropriate CSS files based on settings
             * @param {Object} options - Configuration options
             * @param {string} [options.mode] - The mode to load (light, dark, etc.)
             * @param {string} [options.platform] - The platform to load (desktop, mobile, etc.)
             * @returns {Promise} - Promise that resolves when all stylesheets are loaded
             */
            async loadTheme(options = {}) {
              // Initialize if not already done
              await this.initialize();
              
              const mode = options.mode || this.defaultMode;
              const platform = options.platform || this.defaultPlatform;
          
              const promises = [];
          
              // Load mode CSS
              promises.push(
                this.loadStylesheet(`mode-${mode.toLowerCase()}.css`, `theme-mode-${mode}`)
                  .catch(err => console.warn(`Could not load mode CSS: ${err.message}`))
              );
          
              // Load platform CSS
              promises.push(
                this.loadStylesheet(`platform-${platform.toLowerCase()}.css`, `theme-platform-${platform}`)
                  .catch(err => console.warn(`Could not load platform CSS: ${err.message}`))
              );
          
              // Set data attributes on the document
              this.setThemeAttributes(mode, platform);
          
              return Promise.all(promises);
            }
          }
          
          // Create a global instance
          window.themeLoader = new ThemeLoader();
          
          // Auto-load theme based on default settings
          document.addEventListener('DOMContentLoaded', () => {
            window.themeLoader.loadTheme();
          });
          EOF
      
      - name: Check generated files
        run: |
          echo "Generated CSS files:"
          find src/styles/theme-files -name "*.css" | sort
          
          echo "Total files generated: $(find src/styles/theme-files -type f | wc -l)"
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add src/styles/theme-files/
          git commit -m "Generate theme CSS files with custom processor" || echo "Nothing to commit"
          git push || echo "Nothing to push"